version: "3.8"
name: "aws-cicd_practice"

services:
  server:
    image: dangtong/aws-cicd_env
    container_name: "ide"
    networks:
      - kind_network
    environment:
      FILE__PASSWORD: /run/secrets/code-server-password
    env_file:
      - .env
    working_dir: /code
    ports:
      - "8444:8443"
    secrets:
      - code-server-password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - cloud-cicd-src:/code/cloud-cicd-src
      - vscode:/config
    # depends_on:
    #   server:
    #     condition: service_completed_successfully
networks:
  kind_network:
    name: kind
    external: true

volumes:
  cloud-cicd-src:
    external: true
    name: cloud-cicd-src
  vscode:
    external: true
    name: vscode
secrets:
  code-server-password:
    file: password.txt